/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizoop2;

/**
 *
 * @author elva
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import Connection.koneksi;

public class PesanTiket extends javax.swing.JFrame {

    private static Connection koneksi = new koneksi().with();
    Object o[] = new Object[4];
    static boolean kursi[] = new boolean[20];
    static int selected[] = new int[20];
    static int jumlah;
    static String display = "";

    public PesanTiket() {

        initComponents();
        infokursi.setEditable(false);
    }

    public void cekButton() {
        try {
            Statement s = koneksi.createStatement();
            String sql = "select id_kursi from pesankursi where id_studio = '" + o[2] + "' and kode_jam ='" + o[3] + "'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                int no = Integer.parseInt(r.getString("id_kursi"));
                System.out.println("ini index = " + no);
                kursi[no - 1] = true;

            }
        } catch (SQLException E) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + E.getMessage());
        }
    }

    public void ambilData() {
        try {
            Statement s = koneksi.createStatement();
            System.out.println("index : " + o[0]);
            String sql = "select m.id_show as id, f.judul_film as judul , s.nama_studio as studio ,  j.jam_mulai as jam from showmovie m INNER join film f on f.id_film=m.id_film INNER JOIN studio s on s.id_studio = m.id_studio INNER JOIN jam_tayang j on j.kode_jam= m.kode_jam where m.id_show='" + o[0] + "';";

            ResultSet r = s.executeQuery(sql);
            r.next();
            Object[] o = new Object[4];
            o[2] = r.getString("judul");
            o[0] = r.getString("studio");
            o[1] = r.getString("jam");

            text_film.setText(o[2].toString());
            text_studio.setText(o[0].toString());

            r.close();
            s.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + e.getMessage());
        }
    }

    public static boolean Buttoncek(int index) {
        if (!kursi[index]) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTittle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabelFilm = new javax.swing.JLabel();
        jLabelStudio = new javax.swing.JLabel();
        jLabeldata = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelPilih = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_film = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        text_studio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        infokursi = new javax.swing.JTextArea();
        jPanelSeating = new javax.swing.JPanel();
        jLabelSeating = new javax.swing.JLabel();
        jButtonSeat1 = new javax.swing.JButton();
        jButtonSeat2 = new javax.swing.JButton();
        jButtonSeat3 = new javax.swing.JButton();
        jButtonSeat4 = new javax.swing.JButton();
        jButtonSeat5 = new javax.swing.JButton();
        jButtonSeat6 = new javax.swing.JButton();
        jButtonSeat7 = new javax.swing.JButton();
        jButtonSeat8 = new javax.swing.JButton();
        jButtonSeat9 = new javax.swing.JButton();
        jButtonSeat10 = new javax.swing.JButton();
        jButtonSeat11 = new javax.swing.JButton();
        jButtonSeat12 = new javax.swing.JButton();
        jButtonSeat13 = new javax.swing.JButton();
        jButtonSeat14 = new javax.swing.JButton();
        jButtonSeat15 = new javax.swing.JButton();
        jButtonSeat16 = new javax.swing.JButton();
        jButtonSeat17 = new javax.swing.JButton();
        jButtonSeat18 = new javax.swing.JButton();
        jButtonSeat19 = new javax.swing.JButton();
        jButtonSeat20 = new javax.swing.JButton();
        jButtonPesan = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jPanelContainer.setBackground(new java.awt.Color(249, 253, 255));
        jPanelContainer.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanelContainer.setPreferredSize(new java.awt.Dimension(800, 527));

        jPanelHeader.setBackground(new java.awt.Color(39, 40, 41));

        jLabelTittle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTittle.setText("Pemesanan Tiket Bioskop");
        jLabelTittle.setToolTipText("");

        title.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("JTIXX");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelFilm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFilm.setText("Film");

        jLabelStudio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStudio.setText("Studio");

        jLabeldata.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabeldata.setText("Data Pelanggan");

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNama.setText("Nama");

        jLabelPilih.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelPilih.setText("Pilih Kursi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("KURSI TERPILIH");

        text_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_filmActionPerformed(evt);
            }
        });

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        text_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_studioActionPerformed(evt);
            }
        });

        infokursi.setColumns(20);
        infokursi.setRows(5);
        jScrollPane1.setViewportView(infokursi);

        jPanelSeating.setBackground(javax.swing.UIManager.getDefaults().getColor("TextField.highlight"));
        jPanelSeating.setPreferredSize(new java.awt.Dimension(577, 198));

        jLabelSeating.setBackground(new java.awt.Color(39, 40, 41));
        jLabelSeating.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelSeating.setText("Screen");

        jButtonSeat1.setText("1");
        jButtonSeat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat1ActionPerformed(evt);
            }
        });

        jButtonSeat2.setText("2");
        jButtonSeat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat2ActionPerformed(evt);
            }
        });

        jButtonSeat3.setText("3");
        jButtonSeat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat3ActionPerformed(evt);
            }
        });

        jButtonSeat4.setText("4");
        jButtonSeat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat4ActionPerformed(evt);
            }
        });

        jButtonSeat5.setText("5");
        jButtonSeat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat5ActionPerformed(evt);
            }
        });

        jButtonSeat6.setText("6");
        jButtonSeat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat6ActionPerformed(evt);
            }
        });

        jButtonSeat7.setText("7");
        jButtonSeat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat7ActionPerformed(evt);
            }
        });

        jButtonSeat8.setText("8");
        jButtonSeat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat8ActionPerformed(evt);
            }
        });

        jButtonSeat9.setText("9");
        jButtonSeat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat9ActionPerformed(evt);
            }
        });

        jButtonSeat10.setText("10");
        jButtonSeat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat10ActionPerformed(evt);
            }
        });

        jButtonSeat11.setText("11");
        jButtonSeat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat11ActionPerformed(evt);
            }
        });

        jButtonSeat12.setText("12");
        jButtonSeat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat12ActionPerformed(evt);
            }
        });

        jButtonSeat13.setText("13");
        jButtonSeat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat13ActionPerformed(evt);
            }
        });

        jButtonSeat14.setText("14");
        jButtonSeat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat14ActionPerformed(evt);
            }
        });

        jButtonSeat15.setText("15");
        jButtonSeat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat15ActionPerformed(evt);
            }
        });

        jButtonSeat16.setText("16");
        jButtonSeat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat16ActionPerformed(evt);
            }
        });

        jButtonSeat17.setText("17");
        jButtonSeat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat17ActionPerformed(evt);
            }
        });

        jButtonSeat18.setText("18");
        jButtonSeat18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat18ActionPerformed(evt);
            }
        });

        jButtonSeat19.setText("19");
        jButtonSeat19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat19ActionPerformed(evt);
            }
        });

        jButtonSeat20.setText("20");
        jButtonSeat20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeatingLayout = new javax.swing.GroupLayout(jPanelSeating);
        jPanelSeating.setLayout(jPanelSeatingLayout);
        jPanelSeatingLayout.setHorizontalGroup(
            jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSeat1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonSeat13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonSeat5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                        .addComponent(jButtonSeat6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSeat7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                        .addComponent(jButtonSeat14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSeat15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSeat2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeat8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeat16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                .addComponent(jButtonSeat3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSeat4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                    .addComponent(jButtonSeat17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSeat18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSeat19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSeat20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                    .addComponent(jButtonSeat9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSeat10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSeat11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonSeat12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabelSeating)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSeatingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonSeat1, jButtonSeat10, jButtonSeat11, jButtonSeat12, jButtonSeat13, jButtonSeat14, jButtonSeat15, jButtonSeat16, jButtonSeat17, jButtonSeat18, jButtonSeat19, jButtonSeat2, jButtonSeat20, jButtonSeat3, jButtonSeat4, jButtonSeat5, jButtonSeat6, jButtonSeat7, jButtonSeat8, jButtonSeat9});

        jPanelSeatingLayout.setVerticalGroup(
            jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeat1)
                            .addComponent(jButtonSeat2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeat3)
                            .addComponent(jButtonSeat4))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeat5)
                            .addComponent(jButtonSeat6)
                            .addComponent(jButtonSeat7)
                            .addComponent(jButtonSeat8)
                            .addComponent(jButtonSeat9)
                            .addComponent(jButtonSeat10)
                            .addComponent(jButtonSeat11)
                            .addComponent(jButtonSeat12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeat17)
                            .addComponent(jButtonSeat18)
                            .addComponent(jButtonSeat19)
                            .addComponent(jButtonSeat20)))
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeat13)
                            .addComponent(jButtonSeat14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeat15)
                            .addComponent(jButtonSeat16))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelSeatingLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonSeat1, jButtonSeat10, jButtonSeat11, jButtonSeat12, jButtonSeat13, jButtonSeat14, jButtonSeat15, jButtonSeat16, jButtonSeat17, jButtonSeat18, jButtonSeat19, jButtonSeat2, jButtonSeat20, jButtonSeat3, jButtonSeat4, jButtonSeat5, jButtonSeat6, jButtonSeat7, jButtonSeat8, jButtonSeat9});

        jButtonPesan.setText("Pesan");
        jButtonPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesanActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.setMaximumSize(new java.awt.Dimension(700, 700));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(700, 500));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(700, 500));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelContainerLayout.createSequentialGroup()
                                    .addComponent(jLabelNama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelContainerLayout.createSequentialGroup()
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelFilm)
                                        .addComponent(jLabelStudio))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(text_studio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(text_film, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabeldata, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelPilih))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(jButtonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jPanelSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34))))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilm))
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStudio)
                            .addComponent(text_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabeldata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNama)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPilih)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        ShowMovie show = new ShowMovie();
        show.setVisible(false);
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesanActionPerformed
        // TODO add your handling code here:
        String nama = jTextFieldNama.getText();
        int harga = 0;

        try {
            String create = "insert into transaksi (nama_pelanggan,total_bayar,tanggal_transaksi) values ('" + nama + "','0',NOW())";
            PreparedStatement t = koneksi.prepareStatement(create);
            t.executeUpdate(create);
            System.out.println("insert to transaksi success");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + e.getMessage());
        }

        try {

            String sql2 = "select id_transaksi from transaksi where nama_pelanggan = '" + nama + "'";
            Statement s = koneksi.createStatement();

            ResultSet r = s.executeQuery(sql2);
            r.next();
            String id = r.getString("id_transaksi");

            for (int i = 0; i < jumlah; i++) {
                String sql = "insert into pesankursi(id_studio,id_kursi,kode_jam) values ('" + o[2] + "','" + selected[i] + "','" + o[3] + "');";
                String sql1 = "select harga from film where id_film = '" + o[1] + "'";

                PreparedStatement mStatement = koneksi.prepareStatement(sql);
                s = koneksi.createStatement();
                mStatement.executeUpdate(sql);
                r = s.executeQuery(sql1);
                r.next();
                int hargaIndividu = Integer.parseInt(r.getString("harga"));
                harga += hargaIndividu;

                String sql3 = "insert into detail_transaksi (tgl_transaksi,id_film,id_studio,id_kursi,kode_jam,nota_id)"
                        + "values (NOW(),'" + o[1] + "','" + o[2] + "','" + selected[i] + "','" + o[3] + "','" + id + "')";
                mStatement = koneksi.prepareStatement(sql3);
                mStatement.executeUpdate(sql3);

                System.out.println("insert to detail success");

                mStatement.close();

            }

            try {
                String update = "update transaksi set total_bayar = '" + harga + "' where id_transaksi='" + id + "'";
                PreparedStatement t = koneksi.prepareStatement(update);
                t.executeUpdate(update);
                System.out.println("set total bayar on transaksi success");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + e.getMessage());
            }
            s.close();

            String info = "Nama Pelanggan\t:" + nama + "\n";
            info += "Jumlah tiket\t:" + jumlah + "\n";
            info += "Total Bayar\t:" + harga + "\n";

            JOptionPane.showMessageDialog(null, "Pesanan berhasil ditambahkan\n" + info);

            this.setVisible(false);
            DetailTransaksi detail = new DetailTransaksi();
            detail.setVisible(true);
        } catch (SQLException E) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + E.getMessage());
        }


    }//GEN-LAST:event_jButtonPesanActionPerformed

    private void jButtonSeat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat12ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(11)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 12\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 12  booked");
        }
    }//GEN-LAST:event_jButtonSeat12ActionPerformed

    private void jButtonSeat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat11ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(10)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 11\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 11  booked");
        }

    }//GEN-LAST:event_jButtonSeat11ActionPerformed

    private void text_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_studioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_studioActionPerformed

    private void text_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_filmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_filmActionPerformed

    private void jButtonSeat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat1ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(0)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 1\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 1  booked");
        }
    }//GEN-LAST:event_jButtonSeat1ActionPerformed

    private void jButtonSeat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat2ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(1)) {
            selected[jumlah] = 2;
            jumlah += 1;
            display += "Kursi no 2\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 2  booked");
        }
    }//GEN-LAST:event_jButtonSeat2ActionPerformed

    private void jButtonSeat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat3ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(2)) {
            selected[jumlah] = 3;
            jumlah += 1;
            display += "Kursi no 3\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 3  booked");
        }
    }//GEN-LAST:event_jButtonSeat3ActionPerformed

    private void jButtonSeat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat4ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(3)) {
            selected[jumlah] = 4;
            jumlah += 1;
            display += "Kursi no 4\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 4  booked");
        }
    }//GEN-LAST:event_jButtonSeat4ActionPerformed

    private void jButtonSeat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat7ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(6)) {
            selected[jumlah] = 7;
            jumlah += 1;
            display += "Kursi no 7\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 7  booked");
        }
    }//GEN-LAST:event_jButtonSeat7ActionPerformed

    private void jButtonSeat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat5ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(4)) {
            selected[jumlah] = 5;
            jumlah += 1;
            display += "Kursi no 5\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 5  booked");
        }
    }//GEN-LAST:event_jButtonSeat5ActionPerformed

    private void jButtonSeat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat6ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(5)) {
            selected[jumlah] = 6;
            jumlah += 1;
            display += "Kursi no 6\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 6  booked");
        }
    }//GEN-LAST:event_jButtonSeat6ActionPerformed

    private void jButtonSeat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat8ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(7)) {
            selected[jumlah] = 8;
            jumlah += 1;
            display += "Kursi no 8\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 8  booked");
        }
    }//GEN-LAST:event_jButtonSeat8ActionPerformed

    private void jButtonSeat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat9ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(8)) {
            selected[jumlah] = 9;
            jumlah += 1;
            display += "Kursi no 9\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 9  booked");
        }
    }//GEN-LAST:event_jButtonSeat9ActionPerformed

    private void jButtonSeat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat10ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(9)) {
            selected[jumlah] = 10;
            jumlah += 1;
            display += "Kursi no 10\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 10  booked");
        }
    }//GEN-LAST:event_jButtonSeat10ActionPerformed

    private void jButtonSeat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat13ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(12)) {
            selected[jumlah] = 13;
            jumlah += 1;
            display += "Kursi no 13\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 13  booked");
        }
    }//GEN-LAST:event_jButtonSeat13ActionPerformed

    private void jButtonSeat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat14ActionPerformed
        if (Buttoncek(13)) {
            selected[jumlah] = 14;
            jumlah += 1;
            display += "Kursi no 14\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 14  booked");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeat14ActionPerformed

    private void jButtonSeat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat15ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(14)) {
            selected[jumlah] = 15;
            jumlah += 1;
            display += "Kursi no 15\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 15  booked");
        }
    }//GEN-LAST:event_jButtonSeat15ActionPerformed

    private void jButtonSeat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat16ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(15)) {
            selected[jumlah] = 16;
            jumlah += 1;
            display += "Kursi no 16\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 16  booked");
        }
    }//GEN-LAST:event_jButtonSeat16ActionPerformed

    private void jButtonSeat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat17ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(16)) {
            selected[jumlah] = 17;
            jumlah += 1;
            display += "Kursi no 17\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 17  booked");
        }
    }//GEN-LAST:event_jButtonSeat17ActionPerformed

    private void jButtonSeat18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat18ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(17)) {
            selected[jumlah] = 18;
            jumlah += 1;
            display += "Kursi no 18\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 18  booked");
        }
    }//GEN-LAST:event_jButtonSeat18ActionPerformed

    private void jButtonSeat19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat19ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(18)) {
            selected[jumlah] = 19;
            jumlah += 1;
            display += "Kursi no 19\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 19  booked");
        }
    }//GEN-LAST:event_jButtonSeat19ActionPerformed

    private void jButtonSeat20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat20ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(19)) {
            selected[jumlah] = 20;
            jumlah += 1;
            display += "Kursi no 20\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 18  booked");
        }
    }//GEN-LAST:event_jButtonSeat20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PesanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infokursi;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPesan;
    private javax.swing.JButton jButtonSeat1;
    private javax.swing.JButton jButtonSeat10;
    private javax.swing.JButton jButtonSeat11;
    private javax.swing.JButton jButtonSeat12;
    private javax.swing.JButton jButtonSeat13;
    private javax.swing.JButton jButtonSeat14;
    private javax.swing.JButton jButtonSeat15;
    private javax.swing.JButton jButtonSeat16;
    private javax.swing.JButton jButtonSeat17;
    private javax.swing.JButton jButtonSeat18;
    private javax.swing.JButton jButtonSeat19;
    private javax.swing.JButton jButtonSeat2;
    private javax.swing.JButton jButtonSeat20;
    private javax.swing.JButton jButtonSeat3;
    private javax.swing.JButton jButtonSeat4;
    private javax.swing.JButton jButtonSeat5;
    private javax.swing.JButton jButtonSeat6;
    private javax.swing.JButton jButtonSeat7;
    private javax.swing.JButton jButtonSeat8;
    private javax.swing.JButton jButtonSeat9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFilm;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelPilih;
    private javax.swing.JLabel jLabelSeating;
    private javax.swing.JLabel jLabelStudio;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabeldata;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSeating;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField text_film;
    private javax.swing.JTextField text_studio;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
