/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quizoop2;

/**
 *
 * @author elva
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import Connection.koneksi;

public class PesanTiket extends javax.swing.JFrame {

    private static Connection koneksi = new koneksi().with();
    Object o[] = new Object[4];
    static boolean kursi[] = new boolean[20];
    static int selected[] = new int[20];
    static int jumlah;
    static String display = "";

    public PesanTiket() {

        initComponents();

        infokursi.setEditable(false);

//        buka_koneksi();
    }

    public void cekButton() {
        try {

//            buka_koneksi();
            Statement s = koneksi.createStatement();
            String sql = "select id_kursi from pesankursi where id_studio = '" + o[2] + "' and kode_jam ='" + o[3] + "'";
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                int no = Integer.parseInt(r.getString("id_kursi"));
                System.out.println("ini index = " + no);
                kursi[no - 1] = true;

            }
        } catch (SQLException E) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + E.getMessage());
        }

    }

    public void ambilData() {
        try {
//            buka_koneksi();

            Statement s = koneksi.createStatement();
            System.out.println("index : " + o[0]);
            String sql = "select m.id_show as id, f.judul_film as judul , s.nama_studio as studio ,  j.jam_mulai as jam from showmovie m INNER join film f on f.id_film=m.id_film INNER JOIN studio s on s.id_studio = m.id_studio INNER JOIN jam_tayang j on j.kode_jam= m.kode_jam where m.id_show='" + o[0] + "';";

            ResultSet r = s.executeQuery(sql);
            r.next();
            Object[] o = new Object[4];
            o[2] = r.getString("judul");
            o[0] = r.getString("studio");
            o[1] = r.getString("jam");

            text_film.setText(o[2].toString());
            text_studio.setText(o[0].toString());

            r.close();
            s.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + e.getMessage());
        }
    }

    private static void buka_koneksi() {
        if (koneksi == null) {
            try {
                String url = "jdbc:mysql://localhost:3306/bioskop";
                String user = "root";
                String password = "";

                koneksi = DriverManager.getConnection(url, user, password);
            } catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            }
        }
    }

    public static boolean Buttoncek(int index) {
        if (!kursi[index]) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContainer = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabelTittle = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabelFilm = new javax.swing.JLabel();
        jLabelStudio = new javax.swing.JLabel();
        jLabeldata = new javax.swing.JLabel();
        jLabelNama = new javax.swing.JLabel();
        jLabelPilih = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        text_film = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        text_studio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        infokursi = new javax.swing.JTextArea();
        jPanelSeating = new javax.swing.JPanel();
        jLabelSeating = new javax.swing.JLabel();
        jButtonSeat1 = new javax.swing.JButton();
        jButtonSeat2 = new javax.swing.JButton();
        jButtonSeat3 = new javax.swing.JButton();
        jButtonSeat4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButtonPesan = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        jPanelContainer.setBackground(new java.awt.Color(249, 253, 255));
        jPanelContainer.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanelContainer.setPreferredSize(new java.awt.Dimension(800, 527));

        jPanelHeader.setBackground(new java.awt.Color(39, 40, 41));

        jLabelTittle.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabelTittle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTittle.setText("Pemesanan Tiket Bioskop");
        jLabelTittle.setToolTipText("");

        title.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("JTIXX");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelFilm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelFilm.setText("Film");

        jLabelStudio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelStudio.setText("Studio");

        jLabeldata.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabeldata.setText("Data Pelanggan");

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNama.setText("Nama");

        jLabelPilih.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabelPilih.setText("Pilih Kursi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("KURSI TERPILIH");

        text_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_filmActionPerformed(evt);
            }
        });

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });

        text_studio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_studioActionPerformed(evt);
            }
        });

        infokursi.setColumns(20);
        infokursi.setRows(5);
        jScrollPane1.setViewportView(infokursi);

        jPanelSeating.setBackground(javax.swing.UIManager.getDefaults().getColor("TextField.highlight"));
        jPanelSeating.setPreferredSize(new java.awt.Dimension(577, 198));

        jLabelSeating.setBackground(new java.awt.Color(39, 40, 41));
        jLabelSeating.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabelSeating.setText("Screen");

        jButtonSeat1.setText("1");
        jButtonSeat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat1ActionPerformed(evt);
            }
        });

        jButtonSeat2.setText("2");
        jButtonSeat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat2ActionPerformed(evt);
            }
        });

        jButtonSeat3.setText("3");
        jButtonSeat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat3ActionPerformed(evt);
            }
        });

        jButtonSeat4.setText("4");
        jButtonSeat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeat4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("12");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("13");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("14");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("15");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("16");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setText("17");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("18");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("19");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("20");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeatingLayout = new javax.swing.GroupLayout(jPanelSeating);
        jPanelSeating.setLayout(jPanelSeatingLayout);
        jPanelSeatingLayout.setHorizontalGroup(
            jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSeat1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSeat2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                .addComponent(jButtonSeat3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSeat4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelSeatingLayout.createSequentialGroup()
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabelSeating)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSeatingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11, jButton12, jButton13, jButton14, jButton15, jButton16, jButton17, jButton18, jButton19, jButton20, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonSeat1, jButtonSeat2, jButtonSeat3, jButtonSeat4});

        jPanelSeatingLayout.setVerticalGroup(
            jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeatingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSeat1)
                            .addComponent(jButtonSeat2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSeat3)
                            .addComponent(jButtonSeat4))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton11)
                            .addComponent(jButton12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton17)
                            .addComponent(jButton18)
                            .addComponent(jButton19)
                            .addComponent(jButton20)))
                    .addGroup(jPanelSeatingLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanelSeatingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton13)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton15)
                            .addComponent(jButton16))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelSeatingLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton10, jButton11, jButton12, jButton13, jButton14, jButton15, jButton16, jButton17, jButton18, jButton19, jButton20, jButton5, jButton6, jButton7, jButton8, jButton9, jButtonSeat1, jButtonSeat2, jButtonSeat3, jButtonSeat4});

        jButtonPesan.setText("Pesan");
        jButtonPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesanActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelContainerLayout = new javax.swing.GroupLayout(jPanelContainer);
        jPanelContainer.setLayout(jPanelContainerLayout);
        jPanelContainerLayout.setHorizontalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelContainerLayout.createSequentialGroup()
                                    .addComponent(jLabelNama)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelContainerLayout.createSequentialGroup()
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelFilm)
                                        .addComponent(jLabelStudio))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(text_studio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(text_film, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabeldata, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabelPilih))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelContainerLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButtonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 39, Short.MAX_VALUE))))
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelContainerLayout.setVerticalGroup(
            jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContainerLayout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_film, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFilm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStudio)
                            .addComponent(text_studio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabeldata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNama)
                            .addComponent(jTextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPilih)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelSeating, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContainerLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18)
                .addGroup(jPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesanActionPerformed
        // TODO add your handling code here:
//        buka_koneksi();
        String nama = jTextFieldNama.getText();
        int harga = 0;

        try {
            String create = "insert into transaksi (nama_pelanggan,total_bayar,tanggal_transaksi) values ('" + nama + "','0',NOW())";
            PreparedStatement t = koneksi.prepareStatement(create);
            t.executeUpdate(create);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + e.getMessage());
        }

        try {

            String sql2 = "select id_transaksi from transaksi where nama_pelanggan = '" + nama + "'";
            Statement s = koneksi.createStatement();

            ResultSet r = s.executeQuery(sql2);
            r.next();
            String id = r.getString("id_transaksi");

            for (int i = 0; i < jumlah; i++) {
                String sql = "insert into pesankursi(id_studio,id_kursi,kode_jam) values ('" + o[2] + "','" + selected[i] + "','" + o[3] + "');";
                String sql1 = "select harga from film where id_film = '" + o[1] + "'";

                PreparedStatement mStatement = koneksi.prepareStatement(sql);
                s = koneksi.createStatement();
                mStatement.executeUpdate(sql);
                r = s.executeQuery(sql1);
                r.next();
                int hargaIndividu = Integer.parseInt(r.getString("harga"));
                harga += hargaIndividu;

                String sql3 = "insert into detail_transaksi (tgl_transaksi,id_film,id_studio,id_kursi,kode_jam,nota_id)"
                        + "values (NOW(),'" + o[1] + "','" + o[2] + "','" + selected[i] + "','" + o[3] + "','" + id + "')";
                mStatement = koneksi.prepareStatement(sql3);
                mStatement.executeUpdate(sql3);

                mStatement.close();

            }

            try {

                String update = "update transaksi set total_bayar = '" + harga + "' where id_transaksi='" + id + "'";
                PreparedStatement t = koneksi.prepareStatement(update);
                t.executeUpdate(update);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + e.getMessage());
            }
            s.close();

        } catch (SQLException E) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan haha " + E.getMessage());
        }


    }//GEN-LAST:event_jButtonPesanActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(11)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 12\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(10)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 11\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void text_studioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_studioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_studioActionPerformed

    private void text_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_filmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_filmActionPerformed

    private void jButtonSeat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat1ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(0)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 1\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Kursi 1  booked");
        }
    }//GEN-LAST:event_jButtonSeat1ActionPerformed

    private void jButtonSeat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat2ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(1)) {
            selected[jumlah] = 2;
            jumlah += 1;
            display += "Kursi no 2\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButtonSeat2ActionPerformed

    private void jButtonSeat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat3ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(2)) {
            selected[jumlah] = 3;
            jumlah += 1;
            display += "Kursi no 3\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButtonSeat3ActionPerformed

    private void jButtonSeat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeat4ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(3)) {
            selected[jumlah] = 1;
            jumlah += 1;
            display += "Kursi no 4\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButtonSeat4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(6)) {
            selected[jumlah] = 7;
            jumlah += 1;
            display += "Kursi no 7\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(4)) {
            selected[jumlah] = 5;
            jumlah += 1;
            display += "Kursi no 5\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(5)) {
            selected[jumlah] = 6;
            jumlah += 1;
            display += "Kursi no 6\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(7)) {
            selected[jumlah] = 8;
            jumlah += 1;
            display += "Kursi no 8\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(8)) {
            selected[jumlah] = 9;
            jumlah += 1;
            display += "Kursi no 9\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(9)) {
            selected[jumlah] = 10;
            jumlah += 1;
            display += "Kursi no 10\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(12)) {
            selected[jumlah] = 13;
            jumlah += 1;
            display += "Kursi no 13\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (Buttoncek(13)) {
            selected[jumlah] = 14;
            jumlah += 1;
            display += "Kursi no 14\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(14)) {
            selected[jumlah] = 15;
            jumlah += 1;
            display += "Kursi no 15\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(15)) {
            selected[jumlah] = 16;
            jumlah += 1;
            display += "Kursi no 16\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(16)) {
            selected[jumlah] = 17;
            jumlah += 1;
            display += "Kursi no 17\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(17)) {
            selected[jumlah] = 18;
            jumlah += 1;
            display += "Kursi no 18\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(18)) {
            selected[jumlah] = 19;
            jumlah += 1;
            display += "Kursi no 19\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if (Buttoncek(19)) {
            selected[jumlah] = 20;
            jumlah += 1;
            display += "Kursi no 20\n";
            infokursi.setText(display);
        } else {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan aa ");
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new PesanTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infokursi;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPesan;
    private javax.swing.JButton jButtonSeat1;
    private javax.swing.JButton jButtonSeat2;
    private javax.swing.JButton jButtonSeat3;
    private javax.swing.JButton jButtonSeat4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFilm;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelPilih;
    private javax.swing.JLabel jLabelSeating;
    private javax.swing.JLabel jLabelStudio;
    private javax.swing.JLabel jLabelTittle;
    private javax.swing.JLabel jLabeldata;
    private javax.swing.JPanel jPanelContainer;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JPanel jPanelSeating;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNama;
    private javax.swing.JTextField text_film;
    private javax.swing.JTextField text_studio;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
